// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffelwsrzhvglfjiobsgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZWx3c3J6aHZnbGZqaW9ic2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzU2OTYsImV4cCI6MjA2NTY1MTY5Nn0.ubb7Bo3vuR9NQsbkBzgkgE6fubKdQIk5qYZesc2jmQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);